### ISSUE TITLE
Team 101 review

### ISSUE THREAD

**Issue by ikraamg** [karthi07/review-articles#1]
Great seeing the unique tools/gems implemented in your capstone. Thanks for sharing!

**Comment by karthi07** [comment]
![review_articles_home](https://user-images.githubusercontent.com/5237154/85111136-8b64c480-b231-11ea-929c-34d0ae9e04b8.png)
![review_home](https://user-images.githubusercontent.com/5237154/85111402-e991a780-b231-11ea-9ef0-bcf16b92f664.png)
![user_profile_page](https://user-images.githubusercontent.com/5237154/85111591-2cec1600-b232-11ea-9f56-f108ebab7e77.png)

![redis](https://user-images.githubusercontent.com/5237154/85112638-8c96f100-b233-11ea-9c59-9746efb2f48f.png)
<img width="41" alt="sidekiq" src="https://user-images.githubusercontent.com/5237154/85112642-8ef94b00-b233-11ea-8942-a5c8327974fd.png">
![reactjs](https://user-images.githubusercontent.com/5237154/85112643-8f91e180-b233-11ea-95b3-3c60f976d1bf.png)

![rails](https://user-images.githubusercontent.com/5237154/85113533-0da2b800-b235-11ea-95ac-31b896096efe.png)
